apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: message-kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      value: "192.168.200.29:9092,192.168.200.30:9092,192.168.200.31:9092"
    - name: authRequired
      value: "false"
    - name: maxMessageBytes
      value: 1024