apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: message-letter
spec:
  topic: lowcode.Letter
  route:  /send
  pubsubname: message-kafka-pubsub
scopes:
- message-letter
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: message-email
spec:
  topic: lowcode.Email
  route:  /send
  pubsubname: message-kafka-pubsub
scopes:
- message-email